name: Access app imoveis streamlit

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Executar todas segundas-feiras (1) e quintas-feiras (4) as 9h e 18h
    - cron:  '5 12,21 * * 1,4'
jobs:
  access_app_imoveis:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install lib pandas
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Install lib selenium
      run: pip install selenium
    - name: Install lib requests
      run: pip install requests
    - name: Install lib bs4
      run: pip install bs4
      
    - name: install chromedriver
      run: |
          sudo apt-get install unzip
          wget -N http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv -f chromedriver /usr/local/share/chromedriver
          sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
          #sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
      
    - name: app_imoveis
      run: |
          pwd;ls;python scrap-streamlit-imoveis.py
